import requests
import json
import os 
import random
import time

class Simulator:
    def __init__(self):
        self.url = "http://localhost:3000"
        self.authSettings = {'email': 'cartoonbr494@gmail.com', 'password': 'utk5veses'}
        self.token = ""
        self.pieces = []
    def authenticate(self):
        request = requests.request("POST", self.url + "/autenticacao/entrar", data=self.authSettings)
        if request.status_code == 200:
            self.token = request.json()["data"]["token"]
            return True
        return False
    def getCategory(self, id):
        # [1, 'Placa de vídeo'],
        #[2, 'Periféricos'],
        #[3, 'Processadores'],
        #[4, 'Refrigeração'],
        #[5, 'Acessórios'],
        #[6, 'Tela'],
        #[7, 'Ambiente'],
        if id == 1:
            return 'Placa de vídeo'
        elif id == 2:
            return 'Periféricos'
        elif id == 3:
            return 'Processadores'
        elif id == 4:
            return 'Refrigeração'
        elif id == 5:
            return 'Acessórios'
        elif id == 6:
            return 'Tela'
        elif id == 7:
            return 'Ambiente'
    def generateItems(self):
        for i in range(7):
            category_id = i + 1
            category_name = self.getCategory(i + 1)
            category = dict(
                id = category_id,
                name = category_name
            )
            product = 'Generated By simulator'
            self.pieces.append(dict(
                    category = category,
                    product = product
                ))
    def generateData(self):
        try:
            x = int(input("Quantia de dados para gerar -> "))
            for i in range(x):
                self.generateItems()
            return True
        except:
            print("Ops..")
            return False
    def insertPieces(self):
        for i, object in enumerate(self.pieces):
            try: 
                req = requests.request("POST", self.url + "/pieces", data=json.dumps(object), headers={
                    "authorization": self.token,
                    "Content-Type": "application/json"
                })
                if req.status_code != 201:
                    print("Piece #" + str(i) + " falhou por request...")
                else:
                    print("Piece #" + str(i) + " inserido...")
            except:
                print("Piece #" + str(i) + " falhou...")
    def insertData(self):
        self.authenticate()
        self.generateData()
        self.insertPieces()

while True:
    os.system("cls") # windows
    choice = input('01 -> Start\n02 -> Stop\n -> ')
    if (choice == '02'):
        break
    else:
        simulate = Simulator()
        simulate.insertData()